(function($){var skipIframe=wpimagelazyload_settings.wpimagelazyloadsetting_skipiframe;var skipParent=wpimagelazyload_settings.wpimagelazyloadsetting_skipparent;var skipAllParent=wpimagelazyload_settings.wpimagelazyloadsetting_skipallparent.split(";");var skipVideo=wpimagelazyload_settings.wpimagelazyloadsetting_skipvideo;var loadonposition=parseInt(wpimagelazyload_settings.wpimagelazyloadsetting_loadonposition);var importantVC=wpimagelazyload_settings.wpimagelazyloadsetting_importantvc;function myClasses(image,skipClasses){if(image instanceof SVGElement===false){var myClasses=image.className.split(' ');if(myClasses.some(function(v){return skipClasses.indexOf(v)>=0;})){return false}else{return true}}}
$('document').ready(function(){var scrollBottom=$(window).scrollTop()+window.innerHeight;$('img').each(function(){if(myClasses(this,skipAllParent)){this.setAttribute('src-backup',this.src);var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;var srcsetbak=$(this).attr('srcset');var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;if(srcsetbak){$(this).attr("srcset-backup",srcsetbak);}
if(scrollBottom<isvisible){this.style.cssText="opacity:0;";this.setAttribute('src','');this.setAttribute('srcset','');}}});if(skipVideo=="false"){$('video').each(function(){if(myClasses(this,skipAllParent)){this.setAttribute('src-backup',this.src);var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;var source=elements.find("source");if(scrollBottom<isvisible){this.style.cssText="opacity:0;";this.setAttribute('src','');for(i=0;i<source.length;i++){source[i].setAttribute('src-backup',source[i].src);source[i].setAttribute('src','');}}}});}
if(skipIframe=="false"){$('iframe').each(function(){if(myClasses(this,skipParent)){this.setAttribute('src-backup',this.src);var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;if(skipParent.length!=0){}else{if(scrollBottom<isvisible){this.setAttribute('src','');this.style.cssText="opacity:0;";}else{this.style.opacity="1";}}}});}
$("*").each(function(){if(myClasses(this,skipAllParent)){if($(this).css('background-image').indexOf('url')>-1){var bg=$(this).css('background-image');$(this).attr("background-image-backup",bg);if(importantVC){$(this).css('cssText','background-image: none !important');}else{$(this).css('background-image','none');}}
var bgbak=$(this).attr("background-image-backup");if(bgbak){var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;if(scrollBottom>=isvisible){if(importantVC){$(this).css('cssText',"background-image: "+bgbak+" !important");}else{$(this).css("background-image",bgbak);}}}}});});$(window).scroll(function(){var scrollBottom=$(window).scrollTop()+window.innerHeight;$('img').each(function(){if(myClasses(this,skipAllParent)){var isLoaded=$(this).attr("src");var isLoaded2=$(this).attr("srcset");var hasBackup=$(this).attr("srcset-backup");var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;if(scrollBottom>=isvisible){if(!isLoaded){this.src=this.getAttribute('src-backup');this.className+=" fadein";this.style.opacity="1";}
if(!isLoaded2){if(hasBackup){$(this).attr("srcset",hasBackup);}}}}});if(skipVideo=="false"){$('video').each(function(){if(myClasses(this,skipAllParent)){var isLoaded=$(this).attr("src");var isLoaded2=$(this).attr("srcset");var hasBackup=$(this).attr("srcset-backup");var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;var source=elements.find("source");if(scrollBottom>=isvisible){if(!isLoaded){this.src=this.getAttribute('src-backup');if(this.classList.contains("fadein")==false){this.className+=" fadein";}
this.style.opacity="1";for(i=0;i<source.length;i++){source[i].src=source[i].getAttribute('src-backup');}}
if(!isLoaded2){if(hasBackup){$(this).attr("srcset",hasBackup);}}}}});}
if(skipIframe=="false"){$('iframe').each(function(){if(myClasses(this,skipParent)){var isLoaded=$(this).attr("src");var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;var hasBackup=$(this).attr("src-backup");if(skipParent.length!=0){var found=$(this).parents().hasClass(skipParent);}
if(scrollBottom>=isvisible){if(!isLoaded){if(found&&skipParent.length!=0){}else{this.src=this.getAttribute('src-backup');this.className+=" fadein";this.style.opacity="1";}}}}});}
$("*").each(function(){if(myClasses(this,skipAllParent)){var bgbak=$(this).attr("background-image-backup");if(bgbak){var elements=$(this);var elementsoffset=elements.offset();var isvisibleOriginal=parseInt(elementsoffset.top);var isvisible=isvisibleOriginal+loadonposition;if(scrollBottom>=isvisible){if($(this).css('background-image').indexOf('url')==-1){if(importantVC){$(this).css('cssText',"background-image: "+bgbak+" !important");}else{$(this).css("background-image",bgbak);}}};}}});});})(jQuery);