(function($){$.fn.sameHeight=function(){var maxHeight=0;return this.each(function(index,elem){$(elem).height('auto');var boxHeight=$(elem).height();maxHeight=Math.max(maxHeight,boxHeight);}).height(maxHeight);};function detect_touchDevice(){if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|BB|PlayBook|IEMobile|Windows Phone|Kindle|Silk|Opera Mini/i.test(navigator.userAgent)){$('body').addClass('touch');}else{$('body').removeClass('touch');}}
function fixColumns(){detect_touchDevice();$('.col-grid .col-four').sameHeight();}
$(window).resize(fixColumns);$(document).ready(fixColumns);$(document).ready(function(){if($('#original.makeMeFirst').length){$('.wwd-tabbed-content.tabs').prepend($('#original.makeMeFirst'));}
$('.wwd-tabbed-content ul.tabs li').click(function(e){if($(this).hasClass('active')){$('div.content.active .close-icon').trigger('click');return;}
var targetName=$(this).attr('id');$('div[name='+targetName+'], div.content.active').toggleClass('inactive active');$('.wwd-tabbed-content ul.tabs li.active').removeClass('active');$(this).addClass('active');history.pushState(null,null,'#'+targetName);});$(document).on('click','div.close-icon',function($this){var targetName=$(this).parent().attr('name');$('div.original, div.content.active').toggleClass('inactive active');$('.wwd-tabbed-content ul.tabs li.active').removeClass('active');history.pushState(null,null,'#'+targetName);getHash()});if($('div.original').length||window.location.hash===""){$('.wwd-tabbed-content ul.tabs li').first().trigger('click');}
getHash()
window.history.pushState(null,null,window.location.href.split('#')[0]);});function getHash(){if(window.location.hash.length){var $tab=$('.wwd-tabbed-content ul.tabs li'+window.location.hash);if($tab.length){$tab.trigger('click');}}}
$(document).ready(function(){$(".tab-titles li").hover(function(){$(".tab-content").removeClass('active');$(".tab-titles li").not(this).removeClass('active');$(this).addClass("active");var selected_tab=$(this).find("a").attr("data-href");$(selected_tab).addClass("active");return false;});$('#main').prepend($('.afterMain'))
if($('#menu-no-navigation').length){$('.fusion-mobile-menu-icons').hide();}});$(document).ready(function(){$('.carousel-wrapper').slick({slidesToShow:1,centerMode:true,variableWidth:true,adaptiveHeight:true});});$(function(){$(document).on('click','.fancybox-youtube',function(){var url=$(this).attr('href');console.log('Sending GA event for video: '+url);gaSendEvent({'hitType':'event','eventCategory':'Videos','eventAction':url,'eventLabel':window.location.pathname});});});window.gaSendEvent=function(details){if('ga'in window&&typeof ga=='function'&&'getAll'in ga&&ga.getAll().length){var gaName='gtm1';var gaNameRetrieved=ga.getAll()[0].get('name');if(gaNameRetrieved.length)
gaName=gaNameRetrieved;ga(gaName+'.send',details);}else{setTimeout(function(){gaSendEvent(details);},1000);}};$(document).ready(function(){$('a[href^="#"]').click(function(){var offsetHeight=75;var id=$(this).attr('href');if($(id).offset()){$('html, body').animate({scrollTop:$($.attr(this,'href')).offset().top-offsetHeight},800);}
return false;});});})(jQuery);